//
// Airline.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Airline: Codable { 


    public var iata: String?
    public var icao: String?
    public var nvls: Int?
    public var publicName: String?

    public init(iata: String?, icao: String?, nvls: Int?, publicName: String?) {
        self.iata = iata
        self.icao = icao
        self.nvls = nvls
        self.publicName = publicName
    }

}
