//
// DestinationPublicName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DestinationPublicName: Codable { 


    public var dutch: String?
    public var english: String?

    public init(dutch: String?, english: String?) {
        self.dutch = dutch
        self.english = english
    }

}
