//
// Destination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Destination: Codable { 


    public enum PublicName: String, Codable, CaseIterable {
        case dutch = "dutch"
        case english = "english"
    }
    public var city: String?
    public var country: Int?
    public var iata: String?
    public var publicName: PublicName?

    public init(city: String?, country: Int?, iata: String?, publicName: PublicName?) {
        self.city = city
        self.country = country
        self.iata = iata
        self.publicName = publicName
    }

}
