//
// Destination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Destination: Codable { 


    public var city: String?
    public var country: String?
    public var iata: String?
    public var publicName: DestinationPublicName?

    public init(city: String?, country: String?, iata: String?, publicName: DestinationPublicName?) {
        self.city = city
        self.country = country
        self.iata = iata
        self.publicName = publicName
    }

}
