//
// FlightList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FlightList: Codable { 


    public var flights: [Flight]?

    public init(flights: [Flight]?) {
        self.flights = flights
    }

}
