//
// WeatherDestination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct WeatherDestination: Codable { 


    public var id: String?
    public var currentConditions: Weather?

    public init(id: String?, currentConditions: Weather?) {
        self.id = id
        self.currentConditions = currentConditions
    }

}
