//
// Weather.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Weather: Codable { 


    public var wdir: Int?
    public var temp: Int?
    public var icon: String?

    public init(wdir: Int?, temp: Int?, icon: String?) {
        self.wdir = wdir
        self.temp = temp
        self.icon = icon
    }

}
