//
// DestinationList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DestinationList: Codable { 


    public var destinations: [Destination]?

    public init(destinations: [Destination]?) {
        self.destinations = destinations
    }

}
