//
// Flight.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Flight: Codable { 


    public var aircraftRegistration: String?
    public var lastUpdatedAt: String?

    public init(aircraftRegistration: String?, lastUpdatedAt: String?) {
        self.aircraftRegistration = aircraftRegistration
        self.lastUpdatedAt = lastUpdatedAt
    }

}
