//
// AirlineList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AirlineList: Codable { 


    public var airlines: [Airline]?

    public init(airlines: [Airline]?) {
        self.airlines = airlines
    }

}
