//
// Airline.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import RealmSwift
import Realm


public class Airline: RealmSwift.Object, Codable {

   @objc public dynamic var iata: String = ""
   @objc dynamic var icao: String = ""
   @objc dynamic var nvls: Int = 0
   @objc dynamic var publicName: String = ""

    enum CodingKeys: String, CodingKey {
        case iata
        case icao
        case nvls
        case publicName
    }

    required init(iata: String, icao: String, nvls: Int, publicName: String) {
        self.iata = iata
        self.icao = icao
        self.nvls = nvls
        self.publicName = publicName
    }
    
    required override init() {
        super.init()
    }
    
    required init(realm: RLMRealm, schema: RLMObjectSchema) {
        super.init()
    }
    
    required init(value: Any, schema: RLMSchema) {
        super.init()
    }
    
    public override static func primaryKey() -> String? {
        return "iata"
    }
}

