//
// AirlineList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Realm
import RealmSwift


public class AirlineList: RealmSwift.Object, Codable {

    var id = UUID().uuidString
    var airlines = List<Airline>()
    
    enum CodingKeys: String, CodingKey {
        case id = "id"
        case airlines
    }
    
    required init(airlines: List<Airline>) {
        self.airlines = airlines
    }
    
    required override init() {
        super.init()
    }

    required init(realm: RLMRealm, schema: RLMObjectSchema) {
        super.init()
    }

    required init(value: Any, schema: RLMSchema) {
        super.init()
    }
    
    public override static func primaryKey() -> String? {
        return "id"
    }
}
